import {
    CurrencyAudIcon,
    CurrencyBchIcon,
    CurrencyBtcIcon,
    CurrencyBusdIcon,
    CurrencyDaiIcon,
    CurrencyEthIcon,
    CurrencyEurIcon,
    CurrencyEursIcon,
    CurrencyUsdtIcon,
    CurrencyGbpIcon,
    CurrencyIdkIcon,
    CurrencyLtcIcon,
    CurrencyPaxIcon,
    CurrencyTusdIcon,
    CurrencyPlaceholderIcon,
    CurrencyUsdIcon,
    CurrencyUsdcIcon,
    CurrencyUsdkIcon,
    CurrencyDemoIcon,
    CurrencyXrpIcon,
    CurrencyAlgoIcon,
    CurrencyAvaxIcon,
    CurrencyBatIcon,
    CurrencyBnbIcon,
    CurrencyDashIcon,
    CurrencyDogeIcon,
    CurrencyDotIcon,
    CurrencyEosIcon,
    CurrencyEtcIcon,
    CurrencyFilIcon,
    CurrencyIotaIcon,
    CurrencyLinkIcon,
    CurrencyMaticIcon,
    CurrencyMkrIcon,
    CurrencyMultiCollateralDaiIcon,
    CurrencyNeoIcon,
    CurrencyNoneIcon,
    CurrencyOmgIcon,
    CurrencyP2PIcon,
    CurrencySingleCollateralDaiIcon,
    CurrencySolIcon,
    CurrencyTerraIcon,
    CurrencyTrxIcon,
    CurrencyUniIcon,
    CurrencyXlmIcon,
    CurrencyXmrIcon,
    CurrencyXtzIcon,
    CurrencyZecIcon,
} from "@deriv/quill-icons";
import type { IconTypes } from "@deriv/quill-icons";

export const currencyIcons: { [key: string]: IconTypes } = {
    aud: CurrencyAudIcon,
    bch: CurrencyBchIcon,
    btc: CurrencyBtcIcon,
    busd: CurrencyBusdIcon,
    dai: CurrencyDaiIcon,
    eth: CurrencyEthIcon,
    eur: CurrencyEurIcon,
    "eur-check": CurrencyEurIcon,
    eurs: CurrencyEursIcon,
    eusdt: CurrencyUsdtIcon,
    gbp: CurrencyGbpIcon,
    idk: CurrencyIdkIcon,
    ltc: CurrencyLtcIcon,
    pax: CurrencyPaxIcon,
    tusd: CurrencyTusdIcon,
    tusdt: CurrencyUsdtIcon,
    unknown: CurrencyPlaceholderIcon,
    usd: CurrencyUsdIcon,
    usdc: CurrencyUsdcIcon,
    usdk: CurrencyUsdkIcon,
    ust: CurrencyUsdtIcon,
    virtual: CurrencyDemoIcon,
    xrp: CurrencyXrpIcon,
    algo: CurrencyAlgoIcon,
    avax: CurrencyAvaxIcon,
    bat: CurrencyBatIcon,
    bnb: CurrencyBnbIcon,
    dash: CurrencyDashIcon,
    doge: CurrencyDogeIcon,
    dot: CurrencyDotIcon,
    eos: CurrencyEosIcon,
    etc: CurrencyEtcIcon,
    fil: CurrencyFilIcon,
    iota: CurrencyIotaIcon,
    link: CurrencyLinkIcon,
    matic: CurrencyMaticIcon,
    mkr: CurrencyMkrIcon,
    mcd: CurrencyMultiCollateralDaiIcon,
    neo: CurrencyNeoIcon,
    none: CurrencyNoneIcon,
    omg: CurrencyOmgIcon,
    p2p: CurrencyP2PIcon,
    scd: CurrencySingleCollateralDaiIcon,
    sol: CurrencySolIcon,
    terra: CurrencyTerraIcon,
    trx: CurrencyTrxIcon,
    uni: CurrencyUniIcon,
    xlm: CurrencyXlmIcon,
    xmr: CurrencyXmrIcon,
    xtz: CurrencyXtzIcon,
    zec: CurrencyZecIcon,
} as const;

interface CurrencyIconProps {
    currency?: string;
    isVirtual?: boolean;
}

export const CurrencyIcon = ({ currency, isVirtual }: CurrencyIconProps) => {
    const Icon = isVirtual
        ? currencyIcons.virtual
        : currencyIcons[currency?.toLowerCase() as keyof typeof currencyIcons] ||
          currencyIcons.unknown;

    return <Icon iconSize="sm" />;
};
