name: Staging Deployment
on:
  push:
    branches: [master]

env:
  NODE_ENV: staging

jobs:
  deploy_staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup_node

      - name: Install dependencies
        uses: ./.github/actions/npm_install_from_cache

      - name: Run tests
        run: npm test

      - name: Build
        uses: ./.github/actions/build
        with:
          RSBUILD_REST_URL: ${{ secrets.RSBUILD_REST_URL }}

      - name: Publish to Staging
        uses: ./.github/actions/publish_to_staging
        with:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PROJECT_NAME: champion-trader
