name: Publish to Cloudflare Pages
description: Deploys the build to Cloudflare Pages
inputs:
  CLOUDFLARE_ACCOUNT_ID:
    description: Cloudflare account ID
    required: true
  CLOUDFLARE_API_TOKEN:
    description: Cloudflare API token
    required: true
  CF_BRANCH:
    description: Branch name for deployment
    required: true
  PROJECT_NAME:
    description: Cloudflare Pages project name
    required: true
runs:
  using: composite
  steps:
    - name: Deploy to Cloudflare Pages
      shell: bash
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
      run: |
        npm i wrangler@3.22.3
        cd dist
        npx wrangler pages deploy . --project-name=${{ inputs.PROJECT_NAME }} --branch=${{ inputs.CF_BRANCH }}
        echo "Preview URL: https://${{ inputs.CF_BRANCH }}.${{ inputs.PROJECT_NAME }}.pages.dev"
